server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8

spring:
  security:
#    user:
#      name: test
#      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: 139622633857-phnd4suq1obco70ajm6mtbu5qtba3qal.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          naver:
            client-id: eHC2CEsGZomidN2hel_m
            client-secret: euxggqkdfF
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.cndurpat9itp.ap-northeast-2.rds.amazonaws.com:3306/study?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: admin
    password: 1q2w3e4r
    
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
 
mybatis:
  mapper-locations:
  - /mappers/*.xml
 
file:
  path: C:/jinil/wonyoung/java20220316/workspace/git/security-wonyoung/upload
  